databases:
  - name: budgetappdb
    databaseName: dbforbudgetapp
    user: userdb

services:
  - type: web
    name: budgetapp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetappdb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
